header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - 'pkg/remote/trans/nhttp2/metadata/metadata.go'
    - 'pkg/remote/trans/nhttp2/codes/codes.go'
    - 'pkg/remote/trans/nhttp2/grpc/http2_client.go'
    - 'pkg/remote/trans/nhttp2/grpc/defaults.go'
    - 'pkg/remote/trans/nhttp2/grpc/transport.go'
    - 'pkg/remote/trans/nhttp2/grpc/flowcontrol.go'
    - 'pkg/remote/trans/nhttp2/grpc/keepalive.go'
    - 'pkg/remote/trans/nhttp2/grpc/controlbuf.go'
    - 'pkg/remote/trans/nhttp2/grpc/bdp_estimator.go'
    - 'pkg/remote/trans/nhttp2/grpc/http2_server.go'
    - 'pkg/remote/trans/nhttp2/grpc/http_util.go'
    - 'pkg/remote/trans/nhttp2/status/status.go'
    - 'pkg/remote/codec/protobuf/error.pb.go'
    - 'pkg/remote/codec/protobuf/test.pb.go'
    - 'pkg/remote/codec/thrift/test.go'

  comment: on-failure
